---

- hosts: all
  gather_facts: false
  become: true

  vars_files:
    - vars/main.yml

  tasks:
    - name: Ensure Node.js app folder exists.
      ansible.builtin.file:
        path: "{{ node_app_location }}"
        state: directory

    - name: Check out app from Github.
      ansible.builtin.git:
        repo: "{{ git_repo }}"
        dest: "{{ node_app_location }}"
        accept_hostkey: true
        force: true
        version: HEAD
      register: app_updated

    - name: Install app dependencies defined in package.json.
      community.general.npm:
        path: "{{ node_app_location }}"
        state: present

    - name: Set owner and groups on app files.
      ansible.builtin.command:
        cmd: "chown -R {{ app_user }}:{{ app_user }} {{ node_app_location }}"
      register: perm_set
      when: app_updated and ansible_user != 'vagrant'
      become: true

    - name: Start PM2 and app.
      ansible.builtin.shell:
        cmd: "PORT={{ guest_port }} pm2 start ecosystem.config.js"
        chdir: "{{ node_app_location }}/"
      when: app_updated
      become: true
      become_user: "{{ app_user }}"
