---
- hosts: all
  gather_facts: false
  roles:
    - role: weareinteractive.pm2
      become: true
      vars:
        pm2_user: "{{ privileged_user }}"
        pm2_upstart: true
        pm2_service_name: cbrm

  vars_files:
    - vars/main.yml

  tasks:
    - name: Ensure Node.js app folder exists.
      file:
        path: "{{ node_app_location }}"
        state: directory

    - name: Check out app from Github.
      git:
        repo: "{{ git_repo }}"
        dest: "{{ node_app_location }}"
        accept_hostkey: true
        force: true
        version: 1.3.0
      register: app_updated

    - name: Install app dependencies defined in package.json.
      npm: "path={{ node_app_location }}/app"

    - name: Check list of running Node.js apps.
      command: pm2 list
      register: app_list
      changed_when: false

    - debug:
        var: app_list

    - name: Start Nodejs app.
      command: "pm2 start {{ node_app_location }}/src/app.js\
                host={{ myhost }} port={{ myport }}"
      when: "app_list.stdout.find(node_app_location + '/app/app.js') == -1"
