---

- hosts: all
  gather_facts: false
  become: true

  vars_files:
    - vars/vault.yml
    - vars/main.yml

  tasks:
    - name: Ensure Node.js app folder exists.
      ansible.builtin.file:
        path: "{{ node_app_location }}"
        state: directory

    - name: Check out app from Github.
      ansible.builtin.git:
        repo: "{{ git_repo }}"
        dest: "{{ node_app_location }}"
        accept_hostkey: true
        force: true
        version: HEAD
      register: app_updated


    - name: Apply App DB config template.
      ansible.builtin.template:
        src: "{{ playbook_dir }}/templates/config.js.j2"
        dest: "{{ node_app_location }}/config/config.js"
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: "0644"

    - name: Install app dependencies defined in package.json.
      ansible.builtin.command:
        cmd: npm install
        chdir: "{{ node_app_location }}"

    - name: Set owner and groups on app files.
      ansible.builtin.command:
        cmd: "chown -R {{ app_user }}:{{ app_user }} {{ node_app_location }}"
      register: perm_set
      when: app_updated and ansible_user != 'vagrant'
      become: true

    - name: Run DB migrations to create tables.
      ansible.builtin.command:
        cmd: "npx sequelize db:migrate"
        chdir: "{{ node_app_location }}"

    - name: Seed DB.
      ansible.builtin.command:
        cmd: "npx sequelize db:seed:all"
        chdir: "{{ node_app_location }}"

    - name: Start Node app using Process Manager.
      ansible.builtin.shell:
        cmd: pm2 start ecosystem.config.js
        chdir: "{{ node_app_location }}"
      when: app_updated
      become: true
      become_user: "{{ app_user }}"
